name: Update Major Version Tag on Release

on:
  release:
    types: [published]  # Trigger the workflow when a new release is published

permissions:
  contents: write

jobs:
  update-major-version-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Determine major version and set environment variable
        id: determine_version
        run: |
          tag_name=${GITHUB_REF##*/}
          major_version=$(echo "$tag_name" | grep -oE '^[0-9]+')
          echo "major_version=v$major_version" >> $GITHUB_ENV

      - name: Force update major version tag
        if: startsWith(github.event.release.tag_name, '1.')  # Only act on tags starting with '1.'
        run: |
          git tag ${{ env.major_version }} ${{ github.sha }}  # Create a new tag pointing to the current commit
          git push origin ${{ env.major_version }} --force  # Push the tag to the remote repository
